services:
  db:
    image: postgres:16-alpine
    container_name: lavadero-db
    environment:
      POSTGRES_DB: gestion_lavadero
      POSTGRES_USER: usuario_dev
      POSTGRES_PASSWORD: password_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: